### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ShonenNoSeishin** [ShonenNoSeishin/LibrenMS-Proxmox-Ceph_Addon#1]
- [x] Adapt the CPU metric to be in percent (to be triggerable)
- [x] Make a deployment script 
- [x] Implement PVE logging throught LibrenMS
- [x] Make a script to deploy logging solution
- [ ] Understand why some VMs has CPU 100% and disk 100% for no reason
